---
- name: Playbook to install darkwizard242 roles locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: true
  roles:
    - darkwizard242.git
    - darkwizard242.unzip
    - darkwizard242.python3
    - darkwizard242.pip
    - darkwizard242.openjdk8
