---
- name: Playbook to install darkwizard242 roles locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: true
  roles:
    - darkwizard242.git
    - darkwizard242.unzip
    - darkwizard242.python3
    - darkwizard242.pip
    - darkwizard242.openjdk8
    - darkwizard242.openrazer
    - darkwizard242.polychromatic
    - darkwizard242.atom
    - darkwizard242.googlechrome
    - darkwizard242.packer
    - darkwizard242.terraform
    - darkwizard242.vagrant
    - darkwizard242.shellcheck
    - darkwizard242.tilix
    # - darkwizard242.jenkinslts
    - darkwizard242.docker
    - darkwizard242.awscli
    - darkwizard242.subversion
    - darkwizard242.ruby
    - darkwizard242.azurecli
    # - darkwizard242.gcloudsdk
    - darkwizard242.awsvault
    - darkwizard242.hugo
    - darkwizard242.scout
    - darkwizard242.inspec
    - darkwizard242.awless
    - darkwizard242.dockercompose
    - darkwizard242.logrotate
    - darkwizard242.asciinema
    - darkwizard242.go
    - darkwizard242.trivy
    - darkwizard242.terraforming
    - darkwizard242.serverspec
    - darkwizard242.subfinder
    - darkwizard242.sslscan
    - darkwizard242.simplescreenrecorder
    - darkwizard242.awsnuke
    - darkwizard242.openvpn
    - darkwizard242.virtualbox
    - darkwizard242.tfsec
    - darkwizard242.jq
    - darkwizard242.lazydocker
    - darkwizard242.locust
    # - darkwizard242.checkov
    - darkwizard242.s3cmd
    - darkwizard242.saws
    - darkwizard242.goofys
    - darkwizard242.mc
    - darkwizard242.nodejs
    - darkwizard242.node_exporter
    - darkwizard242.cloc
    - darkwizard242.stacer
    - darkwizard242.speedtest
    - darkwizard242.httpie
    - darkwizard242.adoptopenjdk
    - darkwizard242.keybase
  vars:
    # CUSTOM VARS FOR THIS PLAYBOOK
    ansible_python_interpreter: /usr/bin/python3

    # Overriding default values for role variables of darkwizard242.git
    git_desired_state: latest

    # Overriding default values for role variables of darkwizard242.unzip
    unzip_desired_state: latest

    # Overriding default values for role variables of darkwizard242.python3
    python3_desired_state: latest

    # Overriding default values for role variables of darkwizard242.pip
    pip_app_package: python3-pip
    pip_desired_state: latest
    pip_upgrade_version: latest

    # Overriding default values for role variables of darkwizard242.openjdk8
    openjdk8_desired_state: latest

    # Overriding default values for role variables of darkwizard242.openrazer
    openrazer_package_desired_state: latest

    # Overriding default values for role variables of darkwizard242.polychromatic
    polychromatic_package_desired_state: latest

    # Overriding default values for role variables of darkwizard242.atom
    atom_desired_state: latest

    # Overriding default values for role variables of darkwizard242.googlechrome
    googlechrome_desired_state: latest

    # Overriding default values for role variables of darkwizard242.packer
    packer_version: 1.7.0
    packer_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.terraform
    terraform_version: 0.14.8
    terraform_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.vagrant
    vagrant_version: 2.2.14
    vagrant_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.shellcheck
    shellcheck_desired_state: latest

    # Overriding default values for role variables of darkwizard242.tilix
    tilix_desired_state: latest

    # Overriding default values for role variables of darkwizard242.jenkinslts
    jenkinslts_desired_state: latest
    jenkinslts_service_desired_state: stopped  # Options are: reloaded, restarted, started, stopped
    jenkinslts_app_check_status_code_retries: 30

    # Overriding default values for role variables of darkwizard242.docker
    docker_apps_desired_state: latest
    docker_service_desired_state: stopped  # Options are: reloaded, restarted, started, stopped

    # Overriding default values for role variables of darkwizard242.awscli_
    awscli_desired_state: latest

    # Overriding default values for role variables of darkwizard242.ruby
    ruby_desired_state: latest

    # Overriding default values for role variables of darkwizard242.awsvault and required modifications
    awsvault_export_file: "{{ ansible_env['HOME'] }}/.bashrc"
    awsvault_export_state: present
    awsvault_export_file_backup: yes
    awsvault_export: 'export AWS_VAULT_BACKEND="file"'
    awsvault_version: 6.2.0
    awsvault_bin_path: /usr/local/bin
    awsvault_file_mode: '0755'

    # Overriding default values for role variables of darkwizard242.hugo
    hugo_version: 0.81.0
    hugo_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.scout
    scout_version: 0.15.1
    scout_bin_permission_mode: '0755'

    # Overriding default values for role variables of darkwizard242.inspec
    inspec_version: 4.28.0

    # Overriding default values for role variables of darkwizard242.awless
    awless_version: 0.1.11
    awless_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.dockercompose
    dockercompose_version: 1.28.5
    dockercompose_bin_path: /usr/local/bin
    dockercompose_file_mode: '0755'

    # Overriding default values for role variables of darkwizard242.asciinema
    asciinema_app_desired_state: latest

    # Overriding default values for role variables of darkwizard242.go
    go_version: 1.16.2

    # Overriding default values for role variables of darkwizard242.trivy
    trivy_app_desired_state: latest

    # Overriding default values for role variables of darkwizard242.terraforming
    terraforming_desired_state: latest
    terraforming_user_install: no
    terraforming_include_dependencies: yes


    # Overriding default values for role variables of darkwizard242.serverspec
    serverspec_desired_state: latest
    serverspec_user_install: no
    serverspec_include_dependencies: yes

    # Overriding default values for role variables of darkwizard242.subfinder
    subfinder_version: 2.4.6
    subfinder_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.sslscan
    sslscan_desired_state: latest

    # Overriding default values for role variables of darkwizard242.simplescreenrecorder
    simplescreenrecorder_desired_state: latest

    # Overriding default values for role variables of darkwizard242.awsnuke
    awsnuke_version: 2.14.0
    awsnuke_config_dir: "/etc/{{ awsnuke_app }}"
    awsnuke_config_dir_mode: '0744'
    awsnuke_config_dir_owner: root
    awsnuke_config_dir_group: root
    awsnuke_template_source: aws-nuke-config.yml.j2
    awsnuke_template_dest: aws-nuke-config.yml
    awsnuke_template_dest_mode: '0744'
    awsnuke_template_dest_owner: root
    awsnuke_template_dest_group: root

    # Overriding default values for role variables of darkwizard242.openvpn
    openvpn_desired_state: latest

    # Overriding default values for role variables of darkwizard242.virtualbox
    virtualbox_version: 6.1
    virtualbox_desired_state: latest

    # Overriding default values for role variables of darkwizard242.tfsec
    tfsec_version: 0.39.10

    # Overriding default values for role variables of darkwizard242.jq
    jq_desired_state: latest

    # Overriding default values for role variables of darkwizard242.lazydocker
    lazydocker_version: '0.10'

    # Overriding default values for role variables of darkwizard242.locust
    locust_desired_state: latest

    # Overriding default values for role variables of darkwizard242.checkov
    checkov_desired_state: latest

    # Overriding default values for role variables of darkwizard242.s3cmd
    s3cmd_desired_state: latest

    # Overriding default values for role variables of darkwizard242.saws
    saws_desired_state: latest

    # Overriding default values for role variables of darkwizard242.goofys
    goofys_desired_state: latest

    # Overriding default values for role variables of darkwizard242.nodejs
    nodejs_app_desired_state: present
    nodejs_version: 14.x

    # Overriding default values for role variables of darkwizard242.node_exporter_app
    node_exporter_version: 1.0.1
    node_exporter_systemd_service_setup: true

    # Overriding default values for role variables of darkwizard242.cloc
    cloc_desired_state: latest

    # Overriding default values for role variables of darkwizard242.stacer
    stacer_desired_state: latest

    # Overriding default values for role variables of darkwizard242.speedtest
    speedtest_desired_state: latest

    # Overriding default values for role variables of darkwizard242.httpie
    httpie_desired_state: latest

    # Overriding default values for role variables of darkwizard242.adoptopenjdk
    adoptopenjdk_desired_state: latest
