---
- name: Playbook to install darkwizard242 roles locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: true
  roles:
    - darkwizard242.git
    - darkwizard242.unzip
    - darkwizard242.python3
    - darkwizard242.pip
    - darkwizard242.openjdk8
    - darkwizard242.openrazer
    - darkwizard242.polychromatic
    - darkwizard242.atom
    - darkwizard242.googlechrome
    - darkwizard242.packer
    - darkwizard242.terraform
    - darkwizard242.vagrant
    - darkwizard242.shellcheck
    - darkwizard242.tilix
    - darkwizard242.jenkinslts
    - darkwizard242.docker
    - darkwizard242.awscli
    - darkwizard242.subversion
    - darkwizard242.ruby
    - darkwizard242.azurecli
    - darkwizard242.awsvault
    - darkwizard242.hugo
    - darkwizard242.scout
    - darkwizard242.inspec
    - darkwizard242.awless
    - darkwizard242.dockercompose
    - darkwizard242.logrotate
    - darkwizard242.asciinema
    - darkwizard242.go
    - darkwizard242.trivy
    - darkwizard242.terraforming
    - darkwizard242.serverspec
    - darkwizard242.subfinder
    - darkwizard242.sslscan
    - darkwizard242.simplescreenrecorder
    - darkwizard242.awsnuke
