---
- name: Playbook to install darkwizard242 roles locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: true
  roles:
    - darkwizard242.git
    - darkwizard242.unzip
    - darkwizard242.python3
    - darkwizard242.pip
    - darkwizard242.adoptopenjdk
    - darkwizard242.openrazer
    - darkwizard242.polychromatic
    - darkwizard242.atom
    - darkwizard242.googlechrome
    - darkwizard242.packer
    - darkwizard242.terraform
    - darkwizard242.vagrant
    - darkwizard242.shellcheck
    - darkwizard242.tilix
    # - darkwizard242.jenkinslts
    - darkwizard242.docker
    - darkwizard242.awscli
    - darkwizard242.subversion
    - darkwizard242.ruby
    - darkwizard242.azurecli
    # - darkwizard242.gcloudsdk
    - darkwizard242.awsvault
    - darkwizard242.hugo
    - darkwizard242.scout
    - darkwizard242.inspec
    - darkwizard242.awless
    - darkwizard242.dockercompose
    - darkwizard242.logrotate
    - darkwizard242.asciinema
    - darkwizard242.go
    - darkwizard242.trivy
    - darkwizard242.terraforming
    - darkwizard242.serverspec
    - darkwizard242.subfinder
    # - darkwizard242.sslscan
    - darkwizard242.simplescreenrecorder
    - darkwizard242.awsnuke
    - darkwizard242.openvpn
    - darkwizard242.virtualbox
    - darkwizard242.tfsec
    - darkwizard242.jq
    - darkwizard242.lazydocker
    - darkwizard242.locust
    - darkwizard242.checkov
    - darkwizard242.s3cmd
    - darkwizard242.saws
    - darkwizard242.goofys
    - darkwizard242.mc
    - darkwizard242.nodejs
    - darkwizard242.node_exporter
    - darkwizard242.cloc
    - darkwizard242.stacer
    - darkwizard242.speedtest
    - darkwizard242.httpie
    - darkwizard242.keybase
    - darkwizard242.onepassword
    - darkwizard242.ulauncher
    # - darkwizard242.msteams
    - darkwizard242.bravebrowser
    - darkwizard242.duf
    - darkwizard242.uget
    - darkwizard242.lens
    - darkwizard242.eksctl
    - darkwizard242.kubectl
    - darkwizard242.cni
    - darkwizard242.containerd
    - darkwizard242.crictl
    - darkwizard242.kubeadm
    - darkwizard242.kubelet
    - darkwizard242.helm
    - darkwizard242.minikube
    - darkwizard242.grype
    - darkwizard242.syft
    - darkwizard242.hadolint
    - darkwizard242.vscode
    - darkwizard242.kubens
    - darkwizard242.helmfile
    - darkwizard242.flux
    - darkwizard242.kubescape
    - darkwizard242.infracost
    - darkwizard242.terrascan
    - darkwizard242.dive
    - darkwizard242.hostctl
    - darkwizard242.mkcert
    - darkwizard242.istioctl
    - darkwizard242.nordvpn

  vars:
    # CUSTOM VARS FOR THIS PLAYBOOK
    ansible_python_interpreter: /usr/bin/python3

    # Overriding default values for role variables of darkwizard242.git
    git_desired_state: latest

    # Overriding default values for role variables of darkwizard242.unzip
    unzip_desired_state: latest

    # Overriding default values for role variables of darkwizard242.python3
    python3_desired_state: latest

    # Overriding default values for role variables of darkwizard242.pip
    pip_app_package: python3-pip
    pip_desired_state: latest
    pip_upgrade_version: latest

    # Overriding default values for role variables of darkwizard242.adoptopenjdk
    adoptopenjdk_desired_state: latest

    # Overriding default values for role variables of darkwizard242.openrazer
    openrazer_package_desired_state: latest

    # Overriding default values for role variables of darkwizard242.polychromatic
    polychromatic_package_desired_state: latest

    # Overriding default values for role variables of darkwizard242.atom
    atom_desired_state: latest

    # Overriding default values for role variables of darkwizard242.googlechrome
    googlechrome_desired_state: latest

    # Overriding default values for role variables of darkwizard242.packer
    packer_version: 1.11.2
    packer_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.terraform
    terraform_version: 1.9.8
    terraform_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.vagrant
    vagrant_version: 2.4.1
    vagrant_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.shellcheck
    shellcheck_desired_state: latest

    # Overriding default values for role variables of darkwizard242.tilix
    tilix_desired_state: latest

    # Overriding default values for role variables of darkwizard242.jenkinslts
    jenkinslts_desired_state: latest
    jenkinslts_service_desired_state: stopped  # Options are: reloaded, restarted, started, stopped
    jenkinslts_app_check_status_code_retries: 30

    # Overriding default values for role variables of darkwizard242.docker
    docker_apps_desired_state: latest
    docker_service_desired_state: stopped  # Options are: reloaded, restarted, started, stopped

    # Overriding default values for role variables of darkwizard242.awscli_
    awscli_desired_state: latest

    # Overriding default values for role variables of darkwizard242.ruby
    ruby_desired_state: latest

    # Overriding default values for role variables of darkwizard242.awsvault and required modifications
    awsvault_export_file: "{{ ansible_env['HOME'] }}/.bashrc"
    awsvault_export_state: present
    awsvault_export_file_backup: yes
    awsvault_export: 'export AWS_VAULT_BACKEND="file"'
    awsvault_version: 7.2.0
    awsvault_bin_path: /usr/local/bin
    awsvault_file_mode: '0755'

    # Overriding default values for role variables of darkwizard242.hugo
    hugo_version: 0.136.4
    hugo_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.scout
    scout_version: 0.15.1
    scout_file_mode: '0755'

    # Overriding default values for role variables of darkwizard242.inspec
    inspec_version: 6.8.1

    # Overriding default values for role variables of darkwizard242.awless
    awless_version: 0.1.11
    awless_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.dockercompose
    dockercompose_version: 2.29.7
    dockercompose_bin_path: /usr/local/bin
    dockercompose_file_mode: '0755'

    # Overriding default values for role variables of darkwizard242.asciinema
    asciinema_app_desired_state: latest

    # Overriding default values for role variables of darkwizard242.go
    go_version: 1.22.4

    # Overriding default values for role variables of darkwizard242.trivy
    trivy_app_desired_state: latest

    # Overriding default values for role variables of darkwizard242.terraforming
    terraforming_desired_state: latest
    terraforming_user_install: no
    terraforming_include_dependencies: yes


    # Overriding default values for role variables of darkwizard242.serverspec
    serverspec_desired_state: latest
    serverspec_user_install: no
    serverspec_include_dependencies: yes

    # Overriding default values for role variables of darkwizard242.subfinder
    subfinder_version: 2.6.6
    subfinder_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.sslscan
    sslscan_desired_state: latest

    # Overriding default values for role variables of darkwizard242.simplescreenrecorder
    simplescreenrecorder_desired_state: latest

    # Overriding default values for role variables of darkwizard242.awsnuke
    awsnuke_version: 2.25.0
    awsnuke_config_dir: "/etc/{{ awsnuke_app }}"
    awsnuke_config_dir_mode: '0744'
    awsnuke_config_dir_owner: root
    awsnuke_config_dir_group: root
    awsnuke_template_source: aws-nuke-config.yml.j2
    awsnuke_template_dest: aws-nuke-config.yml
    awsnuke_template_dest_mode: '0744'
    awsnuke_template_dest_owner: root
    awsnuke_template_dest_group: root

    # Overriding default values for role variables of darkwizard242.openvpn
    openvpn_desired_state: latest

    # Overriding default values for role variables of darkwizard242.virtualbox
    virtualbox_version: 6.1
    virtualbox_desired_state: latest

    # Overriding default values for role variables of darkwizard242.tfsec
    tfsec_version: 1.28.11

    # Overriding default values for role variables of darkwizard242.jq
    jq_desired_state: latest

    # Overriding default values for role variables of darkwizard242.lazydocker
    lazydocker_version: '0.23.3'

    # Overriding default values for role variables of darkwizard242.locust
    locust_desired_state: latest

    # Overriding default values for role variables of darkwizard242.checkov
    checkov_desired_state: latest

    # Overriding default values for role variables of darkwizard242.s3cmd
    s3cmd_desired_state: latest

    # Overriding default values for role variables of darkwizard242.saws
    saws_desired_state: latest

    # Overriding default values for role variables of darkwizard242.goofys
    goofys_version: 0.24.0

    # Overriding default values for role variables of darkwizard242.nodejs
    nodejs_app_desired_state: present
    nodejs_version: 18.x

    # Overriding default values for role variables of darkwizard242.node_exporter_app
    node_exporter_version: 1.5.0
    node_exporter_systemd_service_setup: true

    # Overriding default values for role variables of darkwizard242.cloc
    cloc_desired_state: latest

    # Overriding default values for role variables of darkwizard242.stacer
    stacer_desired_state: latest

    # Overriding default values for role variables of darkwizard242.speedtest
    speedtest_desired_state: latest

    # Overriding default values for role variables of darkwizard242.httpie
    httpie_desired_state: latest

    # Overriding default values for role variables of darkwizard242.keybase
    keybase_desired_state: latest

    # Overriding default values for role variables of darkwizard242.onepassword
    onepassword_desired_state: latest

    # Overriding default values for role variables of darkwizard242.ulauncher
    ulauncher_package_desired_state: latest

    # Overriding default values for role variables of darkwizard242.msteams
    # msteams_desired_state: latest

    # Overriding default values for role variables of darkwizard242.bravebrowser
    bravebrowser_app_desired_state: latest

    # Overriding default values for role variables of darkwizard242.duf
    duf_desired_state: present
    duf_version: 0.8.1

    # Overriding default values for role variables of darkwizard242.uget
    uget_desired_state: latest

    # Overriding default values for role variables of darkwizard242.lens
    lens_desired_state: present

    # Overriding default values for role variables of darkwizard242.eksctl
    eksctl_app: eksctl
    eksctl_version: 0.194.0
    eksctl_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.kubectl
    cni_version: 1.6.0
    cni_plugins_dir: /opt/cni/bin
    cni_plugins_dir_mode: '0755'

    # Overriding default values for role variables of darkwizard242.containerd
    containerd_version: 1.7.23
    containerd_systemd_service_setup: true
    containerd_systemd_service_enable_state: yes
    containerd_systemd_service_state: started

    # Overriding default values for role variables of darkwizard242.crictl
    crictl_app: crictl
    crictl_version: 1.31.1
    crictl_bin_path: /usr/local/bin

    # Overriding default values for role variables of darkwizard242.kubectl
    kubectl_version: 1.31.0
    kubectl_os: linux
    kubectl_arch: amd64
    kubectl_bin_path: /usr/local/bin
    kubectl_file_mode: '0755'

    # Overriding default values for role variables of darkwizard242.kubeadm
    kubeadm_version: 1.31.2
    kubeadm_os: linux
    kubeadm_arch: amd64
    kubeadm_bin_path: /usr/local/bin
    kubeadm_file_mode: '0755'

    # Overriding default values for role variables of darkwizard242.kubelet
    kubelet_version: 1.31.2
    kubelet_os: linux
    kubelet_arch: amd64
    kubelet_bin_path: /usr/local/bin
    kubelet_file_mode: '0755'
    kubelet_systemd_service_setup: true

    # Overriding default values for role variables of darkwizard242.helm
    helm_app: helm
    helm_version: 3.16.2
    helm_os: linux
    helm_arch: amd64

    # Overriding default values for role variables of darkwizard242.minikube
    minikube_app: minikube
    minikube_version: 1.34.0
    minikube_arch: amd64

    # Overriding default values for role variables of darkwizard242.grype
    grype_version: 0.82.2
    grype_os: linux
    grype_arch: amd64

    # Overriding default values for role variables of darkwizard242.grype
    syft_version: 1.14.2
    syft_os: linux
    syft_arch: amd64

    # Overriding default values for role variables of darkwizard242.hadolint
    hadolint_version: 2.12.0
    hadolint_os: Linux
    hadolint_arch: x86_64

    # Overriding default values for role variables of darkwizard242.vscode
    vscode_app_name: code
    vscode_desired_state: latest
    vscode_repo_desired_state: present
    vscode_debian_repo_filename: vscode

    # Overriding default values for role variables of darkwizard242.kubens
    kubens_version: 0.9.5
    kubens_os: linux
    kubens_arch: x86_64

    # Overriding default values for role variables of darkwizard242.helmfile
    helmfile_app: helmfile
    helmfile_version: 0.169.1
    helmfile_os: linux
    helmfile_arch: amd64

    # Overriding default values for role variables of darkwizard242.flux
    flux_app: flux
    flux_version: 2.4.0
    flux_os: linux
    flux_arch: amd64

    # Overriding default values for role variables of darkwizard242.lazygit
    lazygit_version: '0.34'

    # Overriding default values for role variables of darkwizard242.kubescape
    kubescape_version: 3.0.18

    # Overriding default values for role variables of darkwizard242.infracost
    infracost_app: infracost
    infracost_version: 0.10.39
    infracost_os: linux
    infracost_arch: amd64

    # Overriding default values for role variables of darkwizard242.terrascan
    terrascan_app: terrascan
    terrascan_version: 1.19.9
    terrascan_os: Linux
    terrascan_arch: x86_64

    # Overriding default values for role variables of darkwizard242.dive
    dive_app: dive
    dive_version: 0.12.0
    dive_os: linux
    dive_arch: amd64

    # Overriding default values for role variables of darkwizard242.hostctl
    hostctl_app: hostctl
    hostctl_version: 1.1.4
    hostctl_os: linux
    hostctl_arch: 64-bit

    # Overriding default values for role variables of darkwizard242.mkcert
    mkcert_app: mkcert
    mkcert_version: 1.4.4
    mkcert_os: linux
    mkcert_arch: amd64

    # Overriding default values for role variables of darkwizard242.istioctl
    istioctl_app: istioctl
    istioctl_version: 1.23.2
    istioctl_os: linux
    istioctl_arch: amd64

    # Overriding default values for role variables of darkwizard242.nordvpn
    nordvpn_desired_state: latest
