# Install darkwizard242 Ansible Galaxy roles on the system prior to provisioning.

# Ansible role to install git.
- src: darkwizard242.git

# Ansible role to install unzip.
- src: darkwizard242.unzip

# Ansible role to install python3.
- src: darkwizard242.python3

# Ansible role to install pip.
- src: darkwizard242.pip

# Ansible role to install openjdk8.
- src: darkwizard242.openjdk8

# Ansible role to install openrazer.
- src: darkwizard242.openrazer

# Ansible role to install polychromatic.
- src: darkwizard242.polychromatic

# Ansible role to install atom.
- src: darkwizard242.atom

# Ansible role to install googlechrome.
- src: darkwizard242.googlechrome

# Ansible role to install packer.
- src: darkwizard242.packer

# Ansible role to install terraform.
- src: darkwizard242.terraform

# Ansible role to install vagrant.
- src: darkwizard242.vagrant

# Ansible role to install shellcheck.
- src: darkwizard242.shellcheck

# Ansible role to install tilix.
- src: darkwizard242.tilix

# Ansible role to install jenkinslts.
- src: darkwizard242.jenkinslts

# Ansible role to install docker.
- src: darkwizard242.docker

# Ansible role to install awscli.
- src: darkwizard242.awscli

# Ansible role to install subversion.
- src: darkwizard242.subversion

# Ansible role to install ruby.
- src: darkwizard242.ruby

# Ansible role to install azurecli.
- src: darkwizard242.azurecli

# Ansible role to install gclousdk.
- src: darkwizard242.gcloudsdk

# Ansible role to install awsvault.
- src: darkwizard242.awsvault

# Ansible role to install hugo.
- src: darkwizard242.hugo

# Ansible role to install scout.
- src: darkwizard242.scout

# Ansible role to install inspec.
- src: darkwizard242.inspec

# Ansible role to install awless.
- src: darkwizard242.awless

# Ansible role to install docker-compose.
- src: darkwizard242.dockercompose

# Ansible role to install and configure logrotate.
- src: darkwizard242.logrotate

# Ansible role to install asciinema.
- src: darkwizard242.asciinema

# Ansible role to install go.
- src: darkwizard242.go

# Ansible role to install trivy.
- src: darkwizard242.trivy

# Ansible role to install terraforming.
- src: darkwizard242.terraforming

# Ansible role to install serverspec.
- src: darkwizard242.serverspec

# Ansible role to install subfinder.
- src: darkwizard242.subfinder

# Ansible role to install sslscan.
- src: darkwizard242.sslscan

# Ansible role to install simplescreenrecorder.
- src: darkwizard242.simplescreenrecorder

# Ansible role to install awsnuke.
- src: darkwizard242.awsnuke

# Ansible role to install openvpn.
- src: darkwizard242.openvpn

# Ansible role to install virtualbox.
- src: darkwizard242.virtualbox

# Ansible role to install tfsec.
- src: darkwizard242.tfsec

# Ansible role to install jq.
- src: darkwizard242.jq

# Ansible role to install lazydocker.
- src: darkwizard242.lazydocker

# Ansible role to install locust.
- src: darkwizard242.locust

# Ansible role to install checkov.
- src: darkwizard242.checkov
