# Install darkwizard242 Ansible Galaxy roles on the system prior to provisioning.

# Ansible role to install git.
- src: darkwizard242.git

# Ansible role to install unzip.
- src: darkwizard242.unzip

# Ansible role to install python3.
- src: darkwizard242.python3

# Ansible role to install pip.
- src: darkwizard242.pip

# Ansible role to install adoptopenjdk.
- src: darkwizard242.adoptopenjdk

# Ansible role to install openjdk8.
- src: darkwizard242.openjdk8

# Ansible role to install openrazer.
- src: darkwizard242.openrazer

# Ansible role to install polychromatic.
- src: darkwizard242.polychromatic

# Ansible role to install atom.
- src: darkwizard242.atom

# Ansible role to install googlechrome.
- src: darkwizard242.googlechrome

# Ansible role to install packer.
- src: darkwizard242.packer

# Ansible role to install terraform.
- src: darkwizard242.terraform

# Ansible role to install vagrant.
- src: darkwizard242.vagrant

# Ansible role to install shellcheck.
- src: darkwizard242.shellcheck

# Ansible role to install tilix.
- src: darkwizard242.tilix

# Ansible role to install jenkinslts.
- src: darkwizard242.jenkinslts

# Ansible role to install docker.
- src: darkwizard242.docker

# Ansible role to install awscli.
- src: darkwizard242.awscli

# Ansible role to install subversion.
- src: darkwizard242.subversion

# Ansible role to install ruby.
- src: darkwizard242.ruby

# Ansible role to install azurecli.
- src: darkwizard242.azurecli

# Ansible role to install gclousdk.
- src: darkwizard242.gcloudsdk

# Ansible role to install awsvault.
- src: darkwizard242.awsvault

# Ansible role to install hugo.
- src: darkwizard242.hugo

# Ansible role to install scout.
- src: darkwizard242.scout

# Ansible role to install inspec.
- src: darkwizard242.inspec

# Ansible role to install awless.
- src: darkwizard242.awless

# Ansible role to install docker-compose.
- src: darkwizard242.dockercompose

# Ansible role to install and configure logrotate.
- src: darkwizard242.logrotate

# Ansible role to install asciinema.
- src: darkwizard242.asciinema

# Ansible role to install go.
- src: darkwizard242.go

# Ansible role to install trivy.
- src: darkwizard242.trivy

# Ansible role to install terraforming.
- src: darkwizard242.terraforming

# Ansible role to install serverspec.
- src: darkwizard242.serverspec

# Ansible role to install subfinder.
- src: darkwizard242.subfinder

# Ansible role to install sslscan.
- src: darkwizard242.sslscan

# Ansible role to install simplescreenrecorder.
- src: darkwizard242.simplescreenrecorder

# Ansible role to install awsnuke.
- src: darkwizard242.awsnuke

# Ansible role to install openvpn.
- src: darkwizard242.openvpn

# Ansible role to install virtualbox.
- src: darkwizard242.virtualbox

# Ansible role to install tfsec.
- src: darkwizard242.tfsec

# Ansible role to install jq.
- src: darkwizard242.jq

# Ansible role to install lazydocker.
- src: darkwizard242.lazydocker

# Ansible role to install locust.
- src: darkwizard242.locust

# Ansible role to install checkov.
- src: darkwizard242.checkov

# Ansible role to install s3cmd.
- src: darkwizard242.s3cmd

# Ansible role to install saws.
- src: darkwizard242.saws

# Ansible role to install goofys.
- src: darkwizard242.goofys

# Ansible role to install mc.
- src: darkwizard242.mc

# Ansible role to install nodejs.
- src: darkwizard242.nodejs

# Ansible role to install node_exporter.
- src: darkwizard242.node_exporter

# Ansible role to install cloc.
- src: darkwizard242.cloc

# Ansible role to install cis_ubuntu_2004.
- src: darkwizard242.cis_ubuntu_2004

# Ansible role to install stacer.
- src: darkwizard242.stacer

# Ansible role to install speedtest.
- src: darkwizard242.speedtest

# Ansible role to install httpie.
- src: darkwizard242.httpie

# Ansible role to install keybase.
- src: darkwizard242.keybase

# Ansible role to install onepassword.
- src: darkwizard242.onepassword

# Ansible role to install ulauncher.
- src: darkwizard242.ulauncher

# Ansible role to install msteams.
- src: darkwizard242.msteams

# Ansible role to install bravebrowser
- src: darkwizard242.bravebrowser

# Ansible role to install duf
- src: darkwizard242.duf

# Ansible role to install uget
- src: darkwizard242.uget

# Ansible role to install lens
- src: darkwizard242.lens

# Ansible role to install eksctl
- src: darkwizard242.eksctl

# Ansible role to install kubectl
- src: darkwizard242.kubectl

# Ansible role to install cni
- src: darkwizard242.cni

# Ansible role to install containerd
- src: darkwizard242.containerd

# Ansible role to install crictl
- src: darkwizard242.crictl

# Ansible role to install kubeadm
- src: darkwizard242.kubeadm

# Ansible role to install kubelet
- src: darkwizard242.kubelet

# Ansible role to install helm
- src: darkwizard242.helm

# Ansible role to install minikube
- src: darkwizard242.minikube

# Ansible role to install grype
- src: darkwizard242.grype

# Ansible role to install syft
- src: darkwizard242.syft

# Ansible role to install hadolint
- src: darkwizard242.hadolint

# Ansible role to install vscode
- src: darkwizard242.vscode

# Ansible role to install kubens
- src: darkwizard242.kubens

# Ansible role to install helmfile
- src: darkwizard242.helmfile

# Ansible role to install flux
- src: darkwizard242.flux

# Ansible role to install lazygit
- src: darkwizard242.lazygit

# Ansible role to install kubescape
- src: darkwizard242.kubescape

# Ansible role to install infracost
- src: darkwizard242.infracost

# Ansible role to install terrascan
- src: darkwizard242.terrascan

# Ansible role to install dive
- src: darkwizard242.dive

# Ansible role to install hostctl
- src: darkwizard242.hostctl

# Ansible role to install mkcert
- src: darkwizard242.mkcert

# Ansible role to install istioctl
- src: darkwizard242.istioctl

# Ansible role to install nordvpn
- src: darkwizard242.nordvpn
