name: ansible-playground-provisioner

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - feature_*
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Installing python-apt as required for some ansible roles.
      run: |
        echo -e "\nAbout to install python-apt locally.\n"
        sudo apt-get install -y python-apt
    - name: Installing darkwizard242 roles on local system from Ansible Galaxy.
      run: |
        echo -e "\nAbout to install darkwizard242 role from requirements.yml locally.\n"
        ansible-galaxy install -r requirements.yml
    - name: Perform Syntax check of ansible playbook called playbook.yml
      run: |
        echo -e "\nSyntax check of ansible playbook.\n"
        ansible-playbook --syntax-check playbook.yml
    - name: Playbook Installation of darkwizard242 roles on local system.
      run: |
        echo -e "\nAbout to run playbook.yml that installs roles locally.\n"
        ansible-playbook playbook.yml
