name: ansible-playground-provisioner

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - feature_*
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install darkwizard242 roles from Ansible Galaxy.
      run: |
        echo -e "\nAbout to install darkwizard242 role from requirements.yml locally."
        ansible-galaxy install -r requirements.yml
